openapi: 3.0.3
info:
  title: Wedify API
  description: Backend API for Wedify wedding planning application
  version: 0.0.1
  contact:
    name: Wedify Team

servers:
  - url: http://localhost:8081
    description: Development server

paths:
  /health:
    get:
      tags:
        - Health
      summary: Health check endpoint
      description: Returns the current health status of the API
      operationId: getHealth
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /api/v1/auth/signup/email:
    post:
      tags:
        - Auth
      summary: Sign up with email
      description: Registers a new user using email and password.
      operationId: signUpWithEmail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpEmailRequest'
            examples:
              default:
                summary: Basic signup
                value:
                  email: "user@example.com"
                  password: "strongpassword"
              withData:
                summary: With custom user data
                value:
                  email: "john@example.com"
                  password: "secret"
                  data:
                    first_name: "John"
                    age: 24
      responses:
        '200':
          description: Signup result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
              examples:
                confirmationRequired:
                  summary: Confirmation required
                  value:
                    success: true
                    user:
                      id: "uuid"
                      email: "user@example.com"
                      phone: null
                      createdAt: "2024-06-01T12:00:00Z"
                      confirmedAt: null
                    message: "User created, email confirmation required"
                loggedIn:
                  summary: User created and logged in
                  value:
                    success: true
                    user:
                      id: "uuid"
                      email: "user@example.com"
                      phone: null
                      createdAt: "2024-06-01T12:00:00Z"
                      confirmedAt: "2024-06-01T12:01:00Z"
                    message: "User created and logged in"
        '400':
          description: Invalid input or user already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /api/v1/auth/signup/phone:
    post:
      tags:
        - Auth
      summary: Sign up with phone
      description: Registers a new user using phone and password.
      operationId: signUpWithPhone
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpPhoneRequest'
            examples:
              sms:
                summary: SMS channel
                value:
                  phone: "+49123456789"
                  password: "strongpassword"
                  channel: "SMS"
              whatsapp:
                summary: WhatsApp channel
                value:
                  phone: "+49123456789"
                  password: "strongpassword"
                  channel: "WHATSAPP"
      responses:
        '200':
          description: Signup result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
              examples:
                confirmationRequired:
                  summary: Confirmation required
                  value:
                    success: true
                    user:
                      id: "uuid"
                      email: null
                      phone: "+49123456789"
                      createdAt: "2024-06-01T12:00:00Z"
                      confirmedAt: null
                    message: "User created, phone confirmation required"
                loggedIn:
                  summary: User created and logged in
                  value:
                    success: true
                    user:
                      id: "uuid"
                      email: null
                      phone: "+49123456789"
                      createdAt: "2024-06-01T12:00:00Z"
                      confirmedAt: "2024-06-01T12:01:00Z"
                    message: "User created and logged in"
        '400':
          description: Invalid input or user already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /api/v1/auth/login/email:
    post:
      tags:
        - Auth
      summary: Login with email
      description: Log in an existing user with email and password.
      operationId: loginWithEmail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginEmailRequest'
            examples:
              basic:
                summary: Basic login
                value:
                  email: "user@example.com"
                  password: "strongpassword"
      responses:
        '200':
          description: Login result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
              examples:
                success:
                  summary: Logged in
                  value:
                    success: true
                    user:
                      id: "uuid"
                      email: "user@example.com"
                      phone: null
                      createdAt: "2024-06-01T12:00:00Z"
                      confirmedAt: "2024-06-01T12:01:00Z"
                    message: "User logged in successfully"
        '400':
          description: Invalid credentials or input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /api/v1/auth/login/phone:
    post:
      tags:
        - Auth
      summary: Login with phone
      description: Log in an existing user with phone and password.
      operationId: loginWithPhone
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginPhoneRequest'
            examples:
              basic:
                summary: Basic phone login
                value:
                  phone: "+49123456789"
                  password: "strongpassword"
      responses:
        '200':
          description: Login result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
              examples:
                success:
                  summary: Logged in
                  value:
                    success: true
                    user:
                      id: "uuid"
                      email: null
                      phone: "+49123456789"
                      createdAt: "2024-06-01T12:00:00Z"
                      confirmedAt: "2024-06-01T12:01:00Z"
                    message: "User logged in successfully"
        '400':
          description: Invalid credentials or input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - version
        - timestamp
      properties:
        status:
          type: string
          example: healthy
        version:
          type: string
          example: 0.0.1
        timestamp:
          type: integer
          format: int64
          example: 1699900000000
    SignUpEmailRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        redirectUrl:
          type: string
          format: uri
          nullable: true
        data:
          type: object
          additionalProperties: true
          nullable: true
    SignUpPhoneRequest:
      type: object
      required:
        - phone
        - password
      properties:
        phone:
          type: string
        password:
          type: string
          format: password
        channel:
          type: string
          enum: [SMS, WHATSAPP]
          default: SMS
    LoginEmailRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
    LoginPhoneRequest:
      type: object
      required:
        - phone
        - password
      properties:
        phone:
          type: string
        password:
          type: string
          format: password
    AuthUserInfo:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        email:
          type: string
          nullable: true
        phone:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
          nullable: true
        confirmedAt:
          type: string
          format: date-time
          nullable: true
    AuthResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
        user:
          $ref: '#/components/schemas/AuthUserInfo'
          nullable: true
        message:
          type: string
          nullable: true
        error:
          type: string
          nullable: true

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Supabase JWT token
